stages:
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/external/fraud_detection.csv
    - src/features/feature_engineering.py
    outs:
    - data/interim/featured_data.csv
  fraud_dist:
    cmd: python notebooks\univariate_analysis\fraud_dist.py
    deps:
    - data/interim/featured_data.csv
    - notebooks\univariate_analysis\fraud_dist.py
    outs:
    - reports/figures/fraud_distribution.png
  cat:
    cmd: python notebooks/univariate_analysis/cat.py
    deps:
    - data/interim/featured_data.csv
    - notebooks/univariate_analysis/cat.py
    outs:
    - reports/figures/categorical_distribution.png

  num:
    cmd: python notebooks/univariate_analysis/num.py
    deps:
    - data/interim/featured_data.csv
    - notebooks\univariate_analysis\num.py
    outs:
    - reports/figures/numerical_distribution.png
  bivariate:
    cmd: python notebooks/bivariate.py
    deps:
    - data/interim/featured_data.csv
    - notebooks/bivariate.py
    outs:
    - reports/figures/bivariate_analysis/origin_dest_analysis.png
    - reports/figures/bivariate_analysis/amount_distribution.png
    - reports/figures/bivariate_analysis/fraud_by_type.png
    - reports/figures/bivariate_analysis/type_distribution.png
  multivariate:
    cmd: python notebooks/multivariate.py
    deps:
    - data/interim/featured_data.csv
    - notebooks/multivariate.py
    outs:
    - reports/figures/correlation_matrix.png
  splitting:
    cmd: python src/Processing/splitting.py
    deps:
    - data/interim/featured_data.csv
    - src/Processing/splitting.py
    outs:
    - data/processed/split

  onehot:
    cmd: python src/Processing/onehot.py
    deps:
    - data/interim/featured_data.csv
    - src/Processing/onehot.py
    outs:
    - data/processed/ohe

  scale:
    cmd: python src/Processing/scale.py
    deps:
    - data/interim/featured_data.csv
    - src/Processing/scale.py
    outs:
    - data/processed/scaling

  finefeature:
    cmd: python src/Processing/finefeature.py
    deps:
    - data/interim/featured_data.csv
    - src/Processing/scale.py
    outs:
    - data/processed/finefeatures
  dummy:
    cmd: python src/models/dummy/model_building.py
    deps:
    - data/processed/finefeatures/X_train_finalfeatures.csv
    - data/processed/split/y_train.csv
    - src/models/dummy/model_building.py
    outs:
    - models/dummy_model.joblib
  dummy_eval:
    cmd: python src/models/dummy/model_evaluate.py
    deps:
    - data/processed/finefeatures/X_test_finalfeatures.csv
    - data/processed/split/y_test.csv
    - models/dummy_model.joblib
    - src/models/dummy/model_evaluate.py
    outs:
    - metrics/dummy/evaluation_metrics.json
    - metrics/dummy/classification_report.txt

  # logistic:
  #   cmd: python src/models/logistic/model_building.py
  #   deps:
  #   - data/processed/finefeatures/X_train_finalfeatures.csv
  #   - data/processed/split/y_train.csv
  #   - src/models/logistic/model_building.py
  #   outs:
  #   # - models/dummy/dummy_model.joblib
  #   - models/logistic_model.joblib
  # logistic_eval:
  #   cmd: python src/models/logistic/model_evaluate.py
  #   deps:
  #   - data/processed/finefeatures/X_test_finalfeatures.csv
  #   - data/processed/split/y_test.csv
  #   - models/logistic_model.joblib
  #   - src/models/logistic/model_evaluate.py
  #   outs:
  #   - metrics/logistic/evaluation_metrics.json
  #   - metrics/logistic/classification_report.txt

  # SVM:
  #   cmd: python src/models/svm/model_building.py
  #   deps:
  #   - data/processed/finefeatures/X_train_finalfeatures.csv
  #   - data/processed/split/y_train.csv
  #   - src/models/svm/model_building.py
  #   outs:
  #   # - models/dummy/dummy_model.joblib
  #   - models/svm_model.joblib
  # SVM_eval:
  #   cmd: python src/models/svm/model_evaluate.py
  #   deps:
  #   - data/processed/finefeatures/X_test_finalfeatures.csv
  #   - data/processed/split/y_test.csv
  #   - models/svm_model.joblib
  #   - src/models/svm/model_evaluate.py
  #   outs:
  #   - metrics/svm/evaluation_metrics.json
  #   - metrics/svm/classification_report.txt

  # KNN:
  #   cmd: python src/models/knn/model_building.py
  #   deps:
  #   - data/processed/finefeatures/X_train_finalfeatures.csv
  #   - data/processed/split/y_train.csv
  #   - src/models/knn/model_building.py
  #   outs:
  #   # - models/dummy/dummy_model.joblib
  #   - models/knn_model.joblib
  # KNN_eval:
  #   cmd: python src/models/knn/model_evaluate.py
  #   deps:
  #   - data/processed/finefeatures/X_test_finalfeatures.csv
  #   - data/processed/split/y_test.csv
  #   - models/knn_model.joblib
  #   - src/models/knn/model_evaluate.py
  #   outs:
  #   - metrics/knn/evaluation_metrics.json
  #   - metrics/knn/classification_report.txt

  # RandomForest:
  #   cmd: python src/models/rf/model_building.py
  #   deps:
  #   - data/processed/finefeatures/X_train_finalfeatures.csv
  #   - data/processed/split/y_train.csv
  #   - src/models/rf/model_building.py
  #   outs:
  #   # - models/dummy/dummy_model.joblib
  #   - models/rf_model.joblib
  # RandomForest_eval:
  #   cmd: python src/models/rf/model_evaluate.py
  #   deps:
  #   - data/processed/finefeatures/X_test_finalfeatures.csv
  #   - data/processed/split/y_test.csv
  #   - models/rf_model.joblib
  #   - src/models/rf/model_evaluate.py
  #   outs:
  #   - metrics/rf/evaluation_metrics.json
  #   - metrics/rf/classification_report.txt

  xgb:
    cmd: python src/models/xgb/model_building.py
    deps:
    - data/processed/finefeatures/X_train_finalfeatures.csv
    - data/processed/split/y_train.csv
    - src/models/xgb/model_building.py
    outs:
    - models/xgb_model.joblib
  xgb_eval:
    cmd: python src/models/xgb/model_evaluate.py
    deps:
    - data/processed/finefeatures/X_test_finalfeatures.csv
    - data/processed/split/y_test.csv
    - models/xgb_model.joblib
    - src/models/xgb/model_evaluate.py
    outs:
    - metrics/xgb/evaluation_metrics.json
    - metrics/xgb/classification_report.txt
  Make_app_pipeline:
    cmd: python Make_app/preprocess.py
    deps:
    - Make_app/preprocess.py
    - parameters\minmax_scaler.joblib
    - parameters\one_hot_encoder.joblib
  app:
    cmd: streamlit run Make_app/app.py
    deps:
    - Make_app/app.py
    - models/xgb_model.joblib
